<?php

module_load_include('inc', 'emailanonymizer', 'includes/util');
module_load_include('inc', 'emailanonymizer', 'includes/hooks');

/**
 * Implements hook_perm(). 
 */
function emailanonymizer_perm() {
  $items = array();

  $items[] = 'administer email anonymizer';

  return $items;
}

/**
 * Implements hook_menu(). 
 */
function emailanonymizer_menu() {
  $items = array();

  $items['admin/settings/emailanonymizer'] = array(
      'title' => 'Email Anonymizer',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('emailanonymizer_admin_settings_form'),
      'access arguments' => array('administer email anonymizer'),
      'file' => 'includes/admin.inc',
  );

  return $items;
}

function emailanonymizer_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'comment_form') {
     $form['#submit'][] = 'custom_comment_email_anonymization';
  }
}

function custom_comment_email_anonymization($form, &$form_state) {
$name = $form_state['values']['name'];
$original_email = $form_state['values']['mail'];
$encoded_email = emailanonymizer_generate_address();
$created = date("F j, Y, g:i a");
db_query('INSERT INTO {emailanonymizer_email_mapping} (created, sender_name, original_email, encoded_email) VALUES ("%d", "%s", "%s","%s")', $created, $name, $original_email, $encoded_email);
}